### PR TITLE
close to working?

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
@denevers and @jvanulde Can you have a look at this? I'm not quite there but I think I have all the pieces in place. It's all configured to use my localhost for now. If you checkout my "node" branch you can do:
```
mvn package war:war && docker-compose up --build
```
to run this as is.

### CODE REVIEW

**Comment by jvanulde** [comment]
Not sure what I am doing wrong but when I build and deploy `http://localhost:8080/gsip/info/LOD_Node/US_Hydro_LOD_Node_JSONLD` resource doesn't exist.

**Comment by dblodgett-usgs** [comment]
Exactly. My app doesn't map to :8080 Do you get anything at: http://localhost/chyld-pilot/app/index.html ?

**Comment by dblodgett-usgs** [comment]
Stand by, I think I found my bug.

**Comment by dblodgett-usgs** [comment]
Found it. Sorry to bother.

**Pull request closed without merging**
